services:
  roonserver:
    image: mackid1993/docker-roonserver:latest
    container_name: roonserver
    hostname: roonserver
    network_mode: host
    # privileged: true
    environment:
      TZ: "America/New_York"
    volumes:
      - ./app:/app
      - ./data:/data
      - ./music:/music
      - ./backups:/backup
    restart: always
