# .github/workflows/auto-commit.yml
name: Auto Commit Ping

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at 00:00 UTC
  workflow_dispatch:     # Manual trigger

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update timestamp
        run: |
          echo "Last ping: $(date -u)" > .auto-commit.txt

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .auto-commit.txt
          git commit -m "chore: auto-update timestamp" || echo "No changes to commit"
          git push
