name: Scheduled Docker Build and Cleanup

on:
  schedule:
    - cron: '0 5 1 * *'  # 12 AM ET on the 1st (5 AM UTC)
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set image tag
        id: set-tag
        run: echo "TAG=$(date -u +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: Log current time
        run: date -u

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            mackid1993/docker-roonserver:latest
            mackid1993/docker-roonserver:${{ env.TAG }}

  cleanup:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Delete old Docker Hub tags (keep latest 3)
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          REPO_NAME: mackid1993/docker-roonserver
          KEEP_COUNT: 3
        run: |
          TOKEN=$(curl -s -H "Content-Type: application/json" \
            -X POST -d '{"username": "'"$DOCKER_USERNAME"'", "password": "'"$DOCKER_PASSWORD"'"}' \
            https://hub.docker.com/v2/users/login/ | jq -r .token)

          TAGS=$(curl -s -H "Authorization: JWT $TOKEN" \
            "https://hub.docker.com/v2/repositories/$REPO_NAME/tags?page_size=100" | \
            jq -r '.results | sort_by(.last_updated) | .[].name')

          COUNT=0
          for TAG in $TAGS; do
            if [[ "$TAG" == "latest" ]]; then continue; fi
            COUNT=$((COUNT+1))
            if [ $COUNT -le $KEEP_COUNT ]; then continue; fi
            echo "Deleting tag: $TAG"
            curl -s -X DELETE \
              -H "Authorization: JWT $TOKEN" \
              "https://hub.docker.com/v2/repositories/$REPO_NAME/tags/$TAG/"
          done
